version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    links:
        - openhid:openhid
        - rocketchat:rocketchat
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
  mongo:
    image: mongo
    restart: unless-stopped
  openhid:
    build: ./openhid-webapp
    volumes:
      - .:/home/openhid/db
    ports: 
      - "8000"
    depends_on:
      - mongo
    environment:
      VIRTUAL_HOST: "nuilabs.org"
    restart: unless-stopped
  rocketchat:
    image: rocketchat/rocket.chat
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: "chat.nuilabs.org"
    depends_on:
      - mongo