version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
  mongo:
    image: mongo
    restart: unless-stopped
  node:
    image: node
    restart: unless-stopped
  openhid:
    build: ./openhid-webapp
    depends_on:
      - node
      - mongo
    environment:
      VIRTUAL_HOST: "nuilabs.org"
    restart: unless-stopped
  rocketchat:
    image: rocketchat
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: "chat.nuilabs.org"
    depends_on:
      - mongo
      - node